# Generated by Django 5.2 on 2025-06-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('data_birth', models.DateTimeField()),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('hobby', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.CharField(max_length=2083),
        ),
    ]
