# Generated by Django 6.0.7 on 2026-07-28 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_biography_alter_coffee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='data_birth',
            new_name='date_birth',
        ),
        migrations.AlterField(
            model_name='biography',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (digits, spaces, '+', '-', '(', ')' only).", regex='^\\+?[0-9 ()-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.URLField(),
        ),
    ]
