# Generated by Django 6.0.7 on 2026-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0004_normalize_date_birth_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
