# Generated by Django 6.0.7 on 2026-07-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.CharField(choices=[('espresso', 'Espresso'), ('coldbrew', 'Cold Brew'), ('pastries', 'Pastries'), ('beans', 'Beans'), ('offers', 'Special Offers')], default='espresso', max_length=20),
        ),
    ]
