# Generated by Django 6.0.7 on 2026-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
