# Generated by Django 6.0.7 on 2026-07-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0010_coffee_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'permissions': [('view_dashboard', 'Can view sales dashboard')]},
        ),
    ]
